# Generated by Django 5.0.6 on 2024-05-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text2speech', '0002_mp3file_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mp3file',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mp3file',
            name='text',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
